#cloud-config

package_upgrade: true
runcmd:
  - mkdir -p /etc/ecs /ecs /var/log/ecs /var/lib/ecs/data
  - echo "/dev/xvdh /ecs ext4 defaults 0 0" >> /etc/fstab
  - mount -a
  - sysctl fs.inotify.max_user_watches=65535
  - curl -sSL https://get.docker.com/ | sh
  - sed -i 's/^ExecStart=.*/ExecStart=\/usr\/bin\/dockerd -H tcp:\/\/0.0.0.0:2375 -H unix:\/\/\/var\/run\/docker.sock -H fd:\/\/ --tls=false/g' /lib/systemd/system/docker.service
  - systemctl daemon-reload && systemctl restart docker
  - sysctl -w net.ipv4.conf.all.route_localnet=1
  - iptables -t nat -A PREROUTING -p tcp -d 169.254.170.2 --dport 80 -j DNAT --to-destination 127.0.0.1:51679
  - iptables -t nat -A OUTPUT -d 169.254.170.2 -p tcp -m tcp --dport 80 -j REDIRECT --to-ports 51679
  - echo ECS_CLUSTER=${cluster_name} > /etc/ecs/ecs.config
  - >
    docker run --name ecs-agent \
      --detach=true \
      --restart=on-failure:10 \
      --volume=/var/run/docker.sock:/var/run/docker.sock \
      --volume=/var/log/ecs/:/log \
      --volume=/var/lib/ecs/data:/data \
      --net=host \
      --env=ECS_LOGFILE=/log/ecs-agent.log \
      --env=ECS_LOGLEVEL=info \
      --env=ECS_DATADIR=/data \
      --env=ECS_CLUSTER=${cluster_name} \
      --env=ECS_ENABLE_TASK_IAM_ROLE=true \
      --env=ECS_ENABLE_TASK_IAM_ROLE_NETWORK_HOST=true \
      --env=ECS_AVAILABLE_LOGGING_DRIVERS="[\"json-file\",\"syslog\",\"journald\",\"gelf\",\"fluentd\",\"awslogs\"]" \
      amazon/amazon-ecs-agent:latest
